stages:
  - greeting
  - build
  - run

hello world:
  stage: greeting
  script:
    - echo "Hello World"

build_image:
  stage: build
  image:
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}"
                       --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
                       --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"

  only:
    changes:
      - Dockerfile

run_stage:
  stage: run
  image:
    name: gitlab-registry.cern.ch/jzahredd/ljptagger
  script:
    - source /miniconda/bin/activate
    - conda activate rootenv
    - python test.py
