data:
  path_to_test_file: "/sps/atlas/k/khandoga/MySamplesS50/user.mykhando.27420846._000001.tree.root_test.root"  # /sps/atlas/k/khandoga/MySamplesS50/*test*.root /sps/atlas/k/khandoga/MySamplesS50/user.mykhando.27420846._000001.tree.root_test.root
  path_to_outdir: "/sps/atlas/j/jzahredd/LJPTagger/latest/ljptagger/Scores/"

test:
  path_to_combined_ckpt: "/sps/atlas/j/jzahredd/LJPTagger/latest/ljptagger/Models/class_grad0.75_lossp0.001_lrr0.001_s50e200_-0.00632_comb_.pt"
  output_name: "LundTest_adv_e026_0.05661"
  choose_model: LundNet
  learning_rate: 0.0005
  batch_size: 2048
