data:
  path_to_trainfiles: "/sps/atlas/k/khandoga/MySamplesS40/user.mykhando.27366163._000001.tree.root_train.root"  # /sps/atlas/k/khandoga/MySamples90/*_train.root /sps/atlas/k/khandoga/MySamplesS40/user.mykhando.27366163._000001.tree.root_train.root
  path_to_save: "/sps/atlas/j/jzahredd/LJPTagger/latest/ljptagger/Models/"

architecture:
  batch_size: 2058
  test_size: 0.2
  n_epochs: 60
  learning_rate: 0.0005
  save_every_epoch: True
  num_gaussians: 20
  lambda_parameter: 10

classifier:
  path_to_classifier_ckpt: "/sps/atlas/j/jzahredd/LJPTagger/latest/ljptagger/Models/LundNet_longrun_e001_0.24174.pt"
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet

adversary:
  save_adv_every_epoch: True
  adv_model_name: "adv_"
  n_epochs_adv: 20
  path_to_store: "/sps/atlas/j/jzahredd/LJPTagger/latest/ljptagger/"
  model_name: "lund_adv_25_negloss_lambda10__"
