data:
  path_to_trainfiles: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/Trainingfile/user.teris.mixedMC.root" #"/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/Trainingfile/user.teris.10.all.tree.root_train.root"  #"/eos/user/j/jzahredd/JetTagging/LJPTopTagger/5_Signal_and_BKG/*_train.root" 
  #"/eos/user/j/jzahredd/JetTagging/final/Train_Test_split_lxplus/*_train.root"  # /sps/atlas/k/khandoga/MySamplesS40/user.mykhando.27366163._000001.tree.root_train.root
  path_to_save: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/weightlundmixedMC/"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/gitlab/ljptagger/Models/"
  model_name: "LundNet_weighted_MixedMC_2"
  weights_file: "/afs/cern.ch/user/t/teris/ljptagger/flat_weights.root"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/ljptagger/final/flat_weights_tr.root"
  scale_factor: 14.475606

architecture:
  batch_size: 4096
  test_size: 0.2
  n_epochs: 20
  learning_rate: 0.0005
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
  save_every_epoch: True

retrain:
  flag: True
  path_to_ckpt: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/weightlundmixedMC/LundNet_weighted_MixedMCe010_0.21084.pt"
  #"/sps/atlas/k/khandoga/TrainGNN/Models/LundNet_ufob_e012_0.12481.pt"
