data:
  path_to_trainfiles: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/Trainingfile/user.teris.1._000001.tree.root_train.root"
  #"/eos/user/j/jzahredd/JetTagging/final/Train_Test_split_lxplus/*_train.root"  # /sps/atlas/k/khandoga/MySamples90/*_train.root /sps/atlas/k/khandoga/MySamplesS40/user.mykhando.27366163._000001.tree.root_train.root
  path_to_save: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/weightadv/"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/gitlab/ljptagger/Models/"
  weights_file: "/afs/cern.ch/user/t/teris/ljptagger/flat_weights_tr.root"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/ljptagger/final/flat_weights_tr.root"
  scale_factor: 14.475606

architecture:
  batch_size: 2058
  test_size: 0.2
  n_epochs: 60
  learning_rate: 0.0005
  save_every_epoch: True
  num_gaussians: 20
  lambda_parameter: 10 # for the adversarial architecture
  loss_parameter: 0.1 # parameter that appears in the total loss (total loss = loss1 - loss_parameter*loss2)

classifier:
  path_to_classifier_ckpt: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/weightlund/LundNet_weighted_e057_0.06052.pt"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/gitlab/ljptagger/Models/LundNet_weighted_e060_0.27473.pt"
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet

adversary:
  save_adv_every_epoch: True
  adv_model_name: "adv_weighted_"
  n_epochs_adv: 20
  path_to_store: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/weightadv/"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/gitlab/ljptagger/Models/"
