data:
  path_to_trainfiles: "/sps/atlas/k/khandoga/MySamplesS50/user.mykhando.27420846._000001.tree.root_train.root"  # /sps/atlas/k/khandoga/MySamplesS50/*_train.root
  path_to_save: "/sps/atlas/j/jzahredd/LJPTagger/latest/ljptagger/Models/"

architecture:
  batch_size: 2048
  test_size: 0.2
  n_epochs: 60
  learning_rate: 0.0005
  save_every_epoch: True
  num_gaussians: 20
  lambda_parameter: 10

classifier:
  path_to_classifier_ckpt: "/sps/atlas/j/jzahredd/LJPTagger/latest/ljptagger/Models/LundNet_longrun_e001_0.24174.pt"
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet

adversary:
  path_to_adv_model_weights: "/sps/atlas/k/khandoga/TrainGNN/Models/adv_e017_6.22525.pt"
  save_adv_every_epoch: True
  adv_model_name: "adv_"
  n_epochs_adv: 20
  path_to_store: "/sps/atlas/j/jzahredd/LJPTagger/latest/ljptagger/"
  model_name: "lund_adv_25_negloss_lambda10__"

combined:
  lr_ratio: 0.001
  grad_parameter: 0.75
  loss_parameter: 0.001
  lr_optimizer: 0.0005
  n_epochs_common: 200
  save_every_epoch: True
  save_adv_every_epoch: True
  path_to_save_combined: "/sps/atlas/j/jzahredd/LJPTagger/latest/ljptagger/"
