data:
  path_to_trainfiles: "/eos/user/r/rvinasco/JetTagging/LundNet_data/full_splitings/10_Signal_and_BKG/user.rvinasco.30617164*" #"/eos/user/j/jzahredd/JetTagging/final/Train_Test_split_lxplus/*_train.root"  # /sps/atlas/k/khandoga/MySamplesS50/*_train.root

architecture:
  batch_size: 2048
  test_size: 0.2
  num_gaussians: 20

classifier:
  path_to_classifier_ckpt: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/lundnet_class_files/"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/gitlab/ljptagger/Models/LundNet_e060_0.24425.pt"
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet

adversary:
  path_to_adv_model_weights: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/adv_files/"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/gitlab/ljptagger/Models/adv_e020_5.17087.pt"

combined:
  lr_ratio: 0.001
  lambda_parameter: 0.75
  loss_parameter: 0.001
  lr_optimizer: 0.0005
  n_epochs_common: 200
  save_every_epoch: True
  path_to_save_combined: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/combined_files/"
