data:
  path_to_trainfiles: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/Trainingfile/user.teris.10.1.tree.root_train.root"
  #"/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/Trainingfile/user.teris.1._000001.tree.root_train.root"
  #"/eos/user/r/rvinasco/JetTagging/LundNet_data/full_splitings/5_Signal_and_BKG/user.rvinasco.*._000001.tree.root_train.root" #"/eos/user/j/jzahredd/JetTagging/final/Train_Test_split_lxplus/*_train.root"  # /sps/atlas/k/khandoga/MySamples90/*_train.root /sps/atlas/k/khandoga/MySamplesS40/user.mykhando.27366163._000001.tree.root_train.root
  path_to_save: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/adv/"

architecture:
  batch_size: 2058
  test_size: 0.2
  n_epochs: 20
  learning_rate: 0.002
  save_every_epoch: True
  num_gaussians: 20
  lambda_parameter: 20 # for the adversarial architecture
  loss_parameter: 0.05 # parameter that appears in the total loss (total loss = loss1 - loss_parameter*loss2)

classifier:
  path_to_classifier_ckpt: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/lundnet/LundNet_3e019_0.04965.pt"
  #"/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/lundnet/LundNet_e059_0.05765.pt"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/gitlab/ljptagger/Models/LundNet_e060_0.24425.pt"
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet

adversary:
  save_adv_every_epoch: True
  adv_model_name: "adv_20_005again"
  n_epochs_adv: 20
  path_to_store: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/adv/"
