data:
  path_to_trainfiles: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/Trainingfile/user.teris.10.1.tree.root_train.root"
  #"/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/Trainingfile/user.teris.1._000001.tree.root_train.root"
  #
  #"/eos/user/r/rvinasco/JetTagging/LundNet_data/full_splitings/5_Signal_and_BKG/user.rvinasco.*._000001.tree.root_train.root" #"/eos/user/j/jzahredd/JetTagging/final/Train_Test_split_lxplus/*_train.root"  # /sps/atlas/k/khandoga/MySamplesS50/*_train.root

architecture:
  batch_size: 2048
  test_size: 0.2
  num_gaussians: 20

classifier:
  path_to_classifier_ckpt: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/lundnet/LundNet_3e019_0.04965.pt"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/gitlab/ljptagger/Models/LundNet_e060_0.24425.pt"
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet

adversary:
  path_to_adv_model_weights: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/adv/adv_20e020_6.39006.pt"
    #"/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/adv/adv_20_005againe020_5.28958.pt"
  #"/afs/cern.ch/work/j/jzahredd/LJPTagger/gitlab/ljptagger/Models/adv_e020_5.17087.pt"

combined:
  lr_ratio: 4
  lambda_parameter: 20
  loss_parameter: 0.05
  lr_optimizer: 0.0005
  n_epochs_common: 150
  save_every_epoch: True
  path_to_save_combined: "/eos/user/t/tmlinare/Lund_tagger/ljptagger/Models/combined/"
